import {
  faBabyCarriage,
  faBook,
  faBriefcase,
  faCar,
  faCode,
  faCoins,
  faDog,
  faDumbbell,
  faFrog,
  faGift,
  faGlobeAmericas,
  faHeart,
  faHeartbeat,
  faHome,
  faMedal,
  faPalette,
  faPeace,
  faPizzaSlice,
  faPlane,
  faUserGraduate
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  work: faBriefcase,
  family: faHome,
  health: faHeartbeat,
  sport: faDumbbell,
  education: faUserGraduate,
  heart: faHeart,
  travel: faGlobeAmericas,
  art: faPalette,
  dog: faDog,
  money: faCoins,
  car: faCar,
  gift: faGift,
  book: faBook,
  plane: faPlane,
  code: faCode,
  medal: faMedal,
  pizza: faPizzaSlice,
  peace: faPeace,
  frog: faFrog,
  baby: faBabyCarriage
};
