import {
  faBabyCarriage,
  faBook,
  faBriefcase,
  faCar,
  faCode,
  faCoins,
  faComments,
  faDog,
  faDumbbell,
  faGift,
  faGlobeAmericas,
  faHeart,
  faHeartbeat,
  faHome,
  faMedal,
  faPalette,
  faPeace,
  faPizzaSlice,
  faPlane,
  faPoop,
  faSocks,
  faUmbrellaBeach,
  faUserGraduate,
  faUserSecret
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  work: faBriefcase,
  family: faHome,
  heartbeat: faHeartbeat,
  dumbbell: faDumbbell,
  education: faUserGraduate,
  heart: faHeart,
  globe: faGlobeAmericas,
  pallete: faPalette,
  dog: faDog,
  money: faCoins,
  car: faCar,
  gift: faGift,
  book: faBook,
  plane: faPlane,
  code: faCode,
  medal: faMedal,
  pizza: faPizzaSlice,
  peace: faPeace,
  baby: faBabyCarriage,
  poop: faPoop,
  umbrella: faUmbrellaBeach,
  socks: faSocks,
  spy: faUserSecret,
  messages: faComments
};
